### ISSUE TITLE
new lab 

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/oo-meowing-cat#1]
follows macro reading

@jmburges

**Comment by jmburges** [comment]
Left one comment!

**Comment by AnnJohn** [comment]
@SophieDeBenedetto Saw you resolved this issue with commit aa331713ccd826d444116e4f8fc29051db8170cb can we close this issue?

**Comment by SophieDeBenedetto** [comment]
yes closing.
