### ISSUE TITLE
User reports lab specs pass immediately

### ISSUE THREAD

**Issue by matbalez-zz** [learn-co-curriculum/oo-meowing-cat#12]
User: Artem Eremin

Batch: 000

Current Lesson: School Domain Querying

Location: https://learn.co/tracks/web-development-with-ruby-on-rails/object-oriented-ruby/beginning-object-orientation/oo-meowing-cat?track_id=5309&batch_id=76

Bug Description: Too many dogs here, please look at both readme and spec. Also too few specs here, and all of them are passing right after cloning the lab.

**Comment by AnnJohn** [comment]
Fixed issue with dogs, but tests don't pass right after cloning the lab.

Closing the issue
