### ISSUE TITLE
no specs for bonus section

### ISSUE THREAD

**Issue by ipc103** [learn-co-curriculum/oo-meowing-cat#13]
it would be nice if the bonus section had some commented out or pending tests taht students could rely on if they finish the main section

**Comment by aviflombaum** [comment]
I think the bonus section should be ripped out and moved into another lab.

**Comment by jmburges** [comment]
agreed. make the bonus a seperate lab about object relations. We'll use it in a later part of the class. For now just create the lab, and then create an issue on the lab that it needs tests

**Comment by sullysaurus** [comment]
Updated.
